# Generated by Django 5.2.7 on 2025-10-21 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("category", models.CharField(max_length=100)),
                ("publish_date", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
