# Generated by Django 5.2.7 on 2025-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('cap', 'Cap'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('jersey', 'Jersey'), ('keychain', 'Keychain'), ('scarf', 'Scarf')], default='update', max_length=20)),
            ],
        ),
    ]
