# Generated by Django 5.2.6 on 2025-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='merch',
            name='vendor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.CharField(choices=[('cap', 'Cap'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('jersey', 'Jersey'), ('keychain', 'Keychain'), ('scarf', 'Scarf'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='merch',
            name='thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
    ]
