# Generated by Django 5.2.6 on 2025-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_merch_link_merch_vendor_alter_merch_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
