from django import forms
from .models import NationalTeamSchedule, MATCH_CATEGORY_CHOICES

class NationalTeamScheduleForm(forms.ModelForm):
    class Meta:
        model = NationalTeamSchedule
        fields = [
            "home_team",
            "away_team",
            "home_code",
            "away_code",
            "match_date",
            "location",
            "category",
            "home_score",
            "away_score",
            "lineup",
            "review",

            "shots_home",
            "shots_away",
            "shots_on_target_home",
            "shots_on_target_away",
            "possession_home",
            "possession_away",
            "passes_home",
            "passes_away",
            "pass_accuracy_home",
            "pass_accuracy_away",
            "fouls_home",
            "fouls_away",
            "yellow_cards_home",
            "yellow_cards_away",
            "red_cards_home",
            "red_cards_away",
            "offsides_home",
            "offsides_away",
            "corners_home",
            "corners_away",
        ]
        widgets = {
            "home_team": forms.TextInput(attrs={"class": "form-control"}),
            "away_team": forms.TextInput(attrs={"class": "form-control"}),
            "home_code": forms.TextInput(attrs={"class": "form-control", "placeholder": "Misal: id, jp"}),
            "away_code": forms.TextInput(attrs={"class": "form-control", "placeholder": "Misal: us, jp"}),
            "match_date": forms.DateTimeInput(attrs={"type": "datetime-local", "class": "form-control"}),
            "location": forms.TextInput(attrs={"class": "form-control"}),
            "category": forms.Select(choices=MATCH_CATEGORY_CHOICES, attrs={"class": "form-select"}),
            "home_score": forms.NumberInput(attrs={"class": "form-control"}),
            "away_score": forms.NumberInput(attrs={"class": "form-control"}),
            "lineup": forms.Textarea(attrs={"class": "form-control", "rows": 4}),
            "review": forms.Textarea(attrs={"class": "form-control", "rows": 4}),

            # ===== Stats Widgets =====
            "shots_home": forms.NumberInput(attrs={"class": "form-control"}),
            "shots_away": forms.NumberInput(attrs={"class": "form-control"}),
            "shots_on_target_home": forms.NumberInput(attrs={"class": "form-control"}),
            "shots_on_target_away": forms.NumberInput(attrs={"class": "form-control"}),
            "possession_home": forms.NumberInput(attrs={"class": "form-control", "min": 0, "max": 100}),
            "possession_away": forms.NumberInput(attrs={"class": "form-control", "min": 0, "max": 100}),
            "passes_home": forms.NumberInput(attrs={"class": "form-control"}),
            "passes_away": forms.NumberInput(attrs={"class": "form-control"}),
            "pass_accuracy_home": forms.NumberInput(attrs={"class": "form-control", "min": 0, "max": 100}),
            "pass_accuracy_away": forms.NumberInput(attrs={"class": "form-control", "min": 0, "max": 100}),
            "fouls_home": forms.NumberInput(attrs={"class": "form-control"}),
            "fouls_away": forms.NumberInput(attrs={"class": "form-control"}),
            "yellow_cards_home": forms.NumberInput(attrs={"class": "form-control"}),
            "yellow_cards_away": forms.NumberInput(attrs={"class": "form-control"}),
            "red_cards_home": forms.NumberInput(attrs={"class": "form-control"}),
            "red_cards_away": forms.NumberInput(attrs={"class": "form-control"}),
            "offsides_home": forms.NumberInput(attrs={"class": "form-control"}),
            "offsides_away": forms.NumberInput(attrs={"class": "form-control"}),
            "corners_home": forms.NumberInput(attrs={"class": "form-control"}),
            "corners_away": forms.NumberInput(attrs={"class": "form-control"}),
        }
