# Generated by Django 4.2.23 on 2025-10-23 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('home_team', models.CharField(default='Indonesia', max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_code', models.CharField(blank=True, max_length=3, null=True)),
                ('away_code', models.CharField(blank=True, max_length=3, null=True)),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('FIFA Matchday A', 'FIFA Matchday A'), ('FIFA Matchday B', 'FIFA Matchday B'), ('AFF Championship', 'AFF Championship'), ('AFC Qualifiers', 'AFC Qualifiers'), ('AFC Cup', 'AFC Cup'), ('World Cup Qualifiers', 'World Cup Qualifiers'), ('World Cup', 'World Cup'), ('Other', 'Other')], default='FIFA Matchday A', max_length=20)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lineup', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('shots_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('possession_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('possession_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passes_home', models.PositiveIntegerField(blank=True, null=True)),
                ('passes_away', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_accuracy_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pass_accuracy_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yellow_cards_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yellow_cards_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_cards_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_cards_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offsides_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offsides_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corners_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corners_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'National Team Schedule',
                'verbose_name_plural': 'National Team Schedules',
                'ordering': ['-match_date'],
            },
        ),
    ]
