# Generated by Django 5.2.7 on 2025-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('club', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('caps', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
