# Generated by Django 5.2.7 on 2025-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='position1',
            field=models.CharField(blank=True, choices=[('', '—'), ('GK', 'GK'), ('LWB', 'LWB'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('RWB', 'RWB'), ('LM', 'LM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('RM', 'RM'), ('LW', 'LW'), ('ST', 'ST'), ('RW', 'RW')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='player',
            name='position2',
            field=models.CharField(blank=True, choices=[('', '—'), ('GK', 'GK'), ('LWB', 'LWB'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('RWB', 'RWB'), ('LM', 'LM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('RM', 'RM'), ('LW', 'LW'), ('ST', 'ST'), ('RW', 'RW')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='player',
            name='position3',
            field=models.CharField(blank=True, choices=[('', '—'), ('GK', 'GK'), ('LWB', 'LWB'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('RWB', 'RWB'), ('LM', 'LM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('RM', 'RM'), ('LW', 'LW'), ('ST', 'ST'), ('RW', 'RW')], default='', max_length=4),
        ),
    ]
