# Generated by Django 5.2.6 on 2025-10-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('img_team1', models.ImageField(upload_to='tickets/teams/')),
                ('img_team2', models.ImageField(upload_to='tickets/teams/')),
                ('img_arena', models.ImageField(blank=True, null=True, upload_to='tickets/arenas/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('vendor_link', models.URLField()),
                ('price', models.IntegerField()),
                ('img_vendor', models.ImageField(upload_to='tickets/vendors/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ticket.ticketmatch')),
            ],
        ),
    ]
