# Generated by Django 5.2.6 on 2025-10-22 08:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticketmatch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='img_vendor',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ticketmatch',
            name='img_arena',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmatch',
            name='img_team1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ticketmatch',
            name='img_team2',
            field=models.URLField(),
        ),
    ]
