# Generated by Django 5.2.6 on 2025-10-22 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketlink_uuid_ticketmatch_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketmatch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
