# Generated by Django 5.2.7 on 2025-10-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketlink_uuid_alter_ticketmatch_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlink',
            old_name='uuid',
            new_name='link_id',
        ),
        migrations.RenameField(
            model_name='ticketmatch',
            old_name='uuid',
            new_name='match_id',
        ),
    ]
