# Generated by Django 5.2.7 on 2025-10-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_uuid_ticketlink_link_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketlink',
            options={'ordering': ['-link_id']},
        ),
        migrations.AlterModelOptions(
            name='ticketmatch',
            options={'ordering': ['-match_id']},
        ),
    ]
