# Generated by Django 5.2.7 on 2025-10-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticketlink_options_alter_ticketmatch_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmatch',
            old_name='img_arena',
            new_name='img_cup',
        ),
        migrations.AddField(
            model_name='ticketmatch',
            name='place',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
