# Generated by Django 4.2.23 on 2025-10-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_rename_img_arena_ticketmatch_img_cup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmatch',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
